### ISSUE TITLE
Fix example

### ISSUE THREAD

**Issue by GioviQ** [dotnet/AspNetCore.Docs.it-it#47]
NavigationManager.Uri() =&gt; NavigationManager.Uri

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor la globalizzazione e la localizzazione](https://docs.microsoft.com/it-it/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @GioviQ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment]
I'll patch this in https://github.com/dotnet/AspNetCore.Docs/pull/17647. Thanks @GioviQ!

**Comment by guardrex** [comment]
@CeciAc I merged https://github.com/dotnet/AspNetCore.Docs/pull/17647, so you can close this issue. Thanks again @GioviQ.
