### ISSUE TITLE
Typo appsettings.jssul

### ISSUE THREAD

**Issue by sidinwillis** [dotnet/AspNetCore.Docs.it-it#57]
![image](https://user-images.githubusercontent.com/1774508/97191101-d2962f80-17a6-11eb-8adf-ac9183e142cf.png)

It should be "**appsettings.json**" instead of "**appsettings.jssul**"

Thks

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Provider di configurazione di Azure Key Vault in ASP.NET Core](https://docs.microsoft.com/it-it/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Correct. That file extension should not be translated.

**Comment by Rick-Anderson** [comment]
@sidinwillis  can you reopen this so they can fix the issue.

**Comment by Rick-Anderson** [comment]
@JasonCard  why is `*.json` being translated?

**Comment by JasonCard** [comment]
@Rick-Anderson Unfortunately, MT engine is over-translating the filename "appsettings.json". To prevent this, can the filename be protected by either inline-code or no-loc metadata?

**Comment by Rick-Anderson** [comment]
@JasonCard  yes. Please transfer this to https://github.com/dotnet/AspNetCore.Docs/issues

I'll add appsettings.json to no-loc metadata
cc @scottaddie  @guardrex  @wadepickett

**Comment by JasonCard** [comment]
@Rick-Anderson Thank you, opened [https://github.com/dotnet/AspNetCore.Docs/issues/20307](https://github.com/dotnet/AspNetCore.Docs/issues/20307) and closing this one.

@sidinwillis Thank you for reporting this issue and we'll address this issue by blocking this filename from being localized on English content side.
