### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by invertostringhe** [dotnet/AspNetCore.Docs.it-it#58]
As mentioned in #51 and #56, seems like that products name aren't correctly handled by the automatic translator that generates this documentation.
`:::no-loc(Blazor):::` should be replaced with `Blazor` in the entire document.
---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Creare un' :::no-loc(Blazor)::: app elenco attività](https://docs.microsoft.com/it-it/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This is a known issue that the doc engineers are working to fix.

cc: @JasonCard

**Comment by invertostringhe** [comment]
Sorry, didn't know it.

**Comment by JasonCard** [comment]
@invertostringhe Thank you for reporting this issue and it's now fixed.
