### ISSUE TITLE
Bad italian translation

### ISSUE THREAD

**Issue by teknoraver** [dotnet/AspNetCore.Docs.it-it#63]
Please don't translate `Kestrel` into `gheppio` which is a bird name

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 93ed7bfe-e34c-540c-8cd6-92cbca4c301a
* Version Independent ID: c02fcf64-71fc-d05b-8e0a-87e4c0b97030
* Content: [Usare HTTP/2 con il server Web ASP.NET Core gheppio](https://docs.microsoft.com/it-it/aspnet/core/fundamentals/servers/kestrel/http2?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/http2.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/fundamentals/servers/kestrel/http2.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/dotnet/AspNetCore.Docs/pull/22182 
See #22187
